### ISSUE TITLE
need help for hp omen 15 2018 -- translation indo : bang tolong laptop rusak akibat windows update, fps gak stabil

### ISSUE THREAD

**Issue by Aiki-bot51** [KotoneShiomi/GPU-Passthrough-Nvidia-Optimus#2]
awalnya laptop baik2 aja, entah gimana kalo lagi main game gitu frame yang udh di render gak melalui iGPU nya, jadi setiap kali alt-tab dari game ke app lain itu kayk nge lag dulu terus ganti gpu. terus kalo main game dedicated gpunya 99-100% usage

tapi sekarang entah kenapa kalo alt-tab itu lancar, tapi fps jadi rendah + gak stabil, terus kalo main game usage dGPU-nya jadi cuman 40-80%. kayaknya karena dulu kan nvidia control panel yang nentuin gpu apa yng dipake, tapi sejak widnows yang nentuin jadi aneh.

udh nyoba 1,5 tahun kagak kelar, terus juga aftersales gak bantu samsek, udh nyoba quick reset juga, install driver lama, dll.

model number: dc00036tx
cpu: intel i78750h
gpu: gtx 1050ti
os: windows 10 build 22H2, terakhir inget stabil di build 1809

**Comment by Alamputraaf** [comment]
> awalnya laptop baik2 aja, entah gimana kalo lagi main game gitu frame yang udh di render gak melalui iGPU nya, jadi setiap kali alt-tab dari game ke app lain itu kayk nge lag dulu terus ganti gpu. terus kalo main game dedicated gpunya 99-100% usage
> 
> tapi sekarang entah kenapa kalo alt-tab itu lancar, tapi fps jadi rendah + gak stabil, terus kalo main game usage dGPU-nya jadi cuman 40-80%. kayaknya karena dulu kan nvidia control panel yang nentuin gpu apa yng dipake, tapi sejak widnows yang nentuin jadi aneh.
> 
> udh nyoba 1,5 tahun kagak kelar, terus juga aftersales gak bantu samsek, udh nyoba quick reset juga, install driver lama, dll.
> 
> model number: dc00036tx cpu: intel i78750h gpu: gtx 1050ti os: windows 10 build 22H2, terakhir inget stabil di build 1809

Maaf mas baru sempat lihat notif dari email masuk. Semoga saranku bisa ngatasin permasalahan masnya

1. Karena ada update versi Qemu 8.0.3, saran saya mas update ke versi terbaru,
2. Coba setting di windows ke Maximum performance
3.  Uninstall driver Nvidia pake ddu, terus install Driver nvidianya pake Nvclean install
4. Klo masih tetep ada frame shutter pas alt tab, setting di vm manager windowsnya, bagian cpu socket nya disesuaikan sama processor masnya : 
Contoh: Ryzen 5 4600h (12cpus total 6c 12t)
Socket :1
Cores;5
Thread:2
Total saya berikan ke VM Windows ada 10 cpus, sisanya yg 2 core untuk Linux
5. Disarankan pake os windowsnya kaya Ghost Spectre / Atlas OS biar optimisasinya lebih bagus.
6. Jika memang masih ngedrop / shutter, coba dibandingkan sama Windows bukan VM, performanya sama apa engga, klo semisal sama mungkin karena overheat belum ganti thermal.
7. Update bios ke ver terbaru, jgn lupa diliat changelog nya dulu sblm update
8. Semoga membantu mas
